### ISSUE TITLE
Clean up models in online 

### ISSUE THREAD

**Issue by sam1am** [Neogoma/stardust-SDK#30]
![image](https://user-images.githubusercontent.com/127555/126880775-56acdc98-3270-4b60-aa02-307444906b85.png)

![image](https://user-images.githubusercontent.com/127555/126880792-4b201406-9be4-472f-9573-24f246a62b15.png)

Here I have scanned an area. A hallway adjacent to this hot tub has appeared disconnected in space and at a scale much smaller than other parts of the scan.  

Currently I think you'd have to re-scan from scratch and delete the current map if it gets messed up at any point. This means you'd have to re-create your scene from scratch and re-align all your content everything.  

It would be ideal to have either: 
1. A way to know earlier in the process that the scan will fail
2. A way to clean up/delete the part of the dataset that has been misplaced or otherwise repair it.

**Comment by handrianj** [comment]
Hi, actually we don't allow operations on the point cloud directly because it's only a visual representation for positioning object but is not linked to the relocation datas.

Did you notice drifting during the mapping ? The problem might come from there. The point cloud is aligned with mapped positions, for now we don't allow modification of any of these datas because it might incur training errors.

If you have an IPhone we suggest you try to use an IPhone for mapping for now. They are less prone to drifting compared to Android ones (We are using and refining datas directly from ARFoundation) and we support cross-platform relocation. We are going to setup some kill-switch on the SDK so if the drifting is too big the mapping is stopped and wrong datas aren't uploaded.

The update is planned on begining of august.

**Comment by handrianj** [comment]
You can also regularly create objects in the mapper to keep an eye on the drifting situation, it's not perfect but it will help keeping an eye on the situation until we send the update

**Comment by sam1am** [comment]
One approach to this might be to allow the deletion of only the previous update. So you could start your scan a bit smaller, and then relocalize and add onto it, but have the ability to fix it if it gets messed up during an update.

**Comment by handrianj** [comment]
> One approach to this might be to allow the deletion of only the previous update.

That's actually a good idea, I'll talk about it with the team!
