### ISSUE TITLE
[BUG] Simple Relocation Tutorial project crashes directly after start.

### ISSUE THREAD

**Issue by Dweeh** [Neogoma/stardust-SDK#41]
After updating the downloaded Simple Relocation Tutorial project to 0.622.unitypackage
app crashes directly after Build And Run or Start.

**Comment by handrianj** [comment]
Hi, thanks for reporting we're currently investigating the issue!

**Comment by handrianj** [comment]
After investigation, the problem was coming from the build settings not from the SDK.
We updated the build settings in the repository.

If you want to modify on your own copy here are the steps to correct:
* Build settings->Player player settings->Other settings->Scripting backend, select IL2CPP
* Build settings-> Compression method, select Default

We've sucessfully build, tested, relocated with this configuration
