### ISSUE TITLE
Map Relocation Problem and Missing Icons

### ISSUE THREAD

**Issue by sharoseali** [Neogoma/stardust-SDK#92]
Hi, Stardust Community. I have tried two different repositories ( **stardust-SD**K and  **metadata tutoria**l) so far, but things are not working as shown in the tutorials. The first issue is that when a repo is cloned either by git or by zip, PNG icons are downloaded in some corrupt form and cannot be displayed either in the system, in the Unity editor, or in the Android app. I have reported the issue before in the Metedata repo, but here this issue also exists.

The second issue is not showing the map at the relocation scene that I have uploaded. It shows on the portal that I have uploaded one map, but when I open Relocation Scene,. It always shows none. This issue also arrives in both Reps. I don't know where I am wrong.

**The Way I run the Unity Project:**
I simply put my stardust API key in Negoma Components and created a build for android
My Android Phone is a Redmi Note 9 with Android 11

Here is my map dashboard screen shot
![stardust](https://github.com/Neogoma/stardust-SDK/assets/19869426/a5249ed9-db9c-4ad3-a3b5-cbcc7801a009)

**Comment by handrianj** [comment]
For the icons issue, the issue has been resolved. We double checked by cloning the repo in a new folder with github desktop and it works properly.

Forr your second issue it's likely because you didn't press the "Train" button after uploading your pictures. In your example you have no pictures uploaded so it's normal that the training process didn't work (or failed).

We suggest using at least 30 pictures in your dataset to have a clear. 

We wrote a mapping guide for our users to understand how to correctly map a place: https://doc.neogoma.com/#/mapping_strategy
